# Generated by Django 5.1.6 on 2025-02-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50, verbose_name='Dish Name')),
                ('dish_status', models.BooleanField(default=True, verbose_name='Dish Status')),
                ('dish_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Order List',
                'verbose_name_plural': 'Order Lists',
            },
        ),
    ]
