# Generated by Django 5.1.6 on 2025-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
